version: '3.3'
services:
  flyway:
    image: flyway/flyway
    volumes:
      - ./sql:/flyway/sql
    environment:
      FLYWAY_URL: ${DB_URL}
      FLYWAY_USER: ${DB_USER}
      FLYWAY_PASSWORD: ${DB_PASSWORD}
    network_mode: host
  db:
    image: mysql
    container_name: helpdesk-ticketing-database
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3386:3306